version: '3.8'
services:
  db_postgres:
    image: postgres:12.9-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  fastapi_backend:
    image: 195917548900.dkr.ecr.us-east-2.amazonaws.com/nexos:v0.0.2
    env_file:
      - .env
    ports:
      - '5000:5000'