version: '3.8'
services:
  db_postgres:
    image: postgres:12.9-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  fastapi_backend:
    # build: .
    image: testing:v1.0.1
    ports:
      - '5000:5000'