"""change primary_key mode

Revision ID: 0374bc4db276
Revises: 5ffd5f2d5be1
Create Date: 2022-10-12 23:48:35.960145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0374bc4db276'
down_revision = '5ffd5f2d5be1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_id', table_name='inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    # ### end Alembic commands ###
