"""int a string

Revision ID: 1011013c26b1
Revises: c8f83b5a152e
Create Date: 2022-10-13 20:13:27.124178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1011013c26b1'
down_revision = 'c8f83b5a152e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory2',
    sa.Column('FechaInventario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GLN_Cliente', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('GLN_sucursal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Gtin_Producto', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Inventario_Final', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PrecioUnidad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
