"""normal

Revision ID: 26c6eec616e0
Revises: 0374bc4db276
Create Date: 2022-10-12 23:55:51.169791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c6eec616e0'
down_revision = '0374bc4db276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
