"""fecha a str

Revision ID: 35516b60ae56
Revises: 872f7f698303
Create Date: 2022-10-13 00:11:48.597741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35516b60ae56'
down_revision = '872f7f698303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
