"""fecha a text

Revision ID: 5ada0aaacc56
Revises: 35516b60ae56
Create Date: 2022-10-13 00:13:51.865092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ada0aaacc56'
down_revision = '35516b60ae56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
