"""fecha a text

Revision ID: 64467008bbef
Revises: 5ada0aaacc56
Create Date: 2022-10-13 00:21:44.414239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64467008bbef'
down_revision = '5ada0aaacc56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FechaInventario', sa.Text(), nullable=True),
    sa.Column('GLN_Cliente', sa.Integer(), nullable=True),
    sa.Column('GLN_sucursal', sa.Integer(), nullable=True),
    sa.Column('Gtin_Producto', sa.Integer(), nullable=True),
    sa.Column('Inventario_Final', sa.Integer(), nullable=True),
    sa.Column('PrecioUnidad', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory2_id'), 'inventory2', ['id'], unique=False)
    op.drop_index('ix_inventory_id', table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('FechaInventario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GLN_Cliente', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('GLN_sucursal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Gtin_Producto', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Inventario_Final', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PrecioUnidad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FechaInventario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GLN_Cliente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GLN_sucursal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Gtin_Producto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Inventario_Final', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PrecioUnidad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    op.drop_index(op.f('ix_inventory2_id'), table_name='inventory2')
    op.drop_table('inventory2')
    # ### end Alembic commands ###
