"""fecha a str

Revision ID: 872f7f698303
Revises: 01b3d31855b8
Create Date: 2022-10-13 00:09:09.221169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '872f7f698303'
down_revision = '01b3d31855b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('FechaInventario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GLN_Cliente', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('GLN_Sucrusal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Gtin_Producto', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Inventario_Final', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PrecioUnidad', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
